name: Lint

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - run: uv run ruff format --check
      - run: uv run ruff check
      - run: uv run pyright
      - run: uv run tombi lint pyproject.toml
      - run: uv run yamllint .
      - run: uv run pymarkdownlnt scan docs *.md -r

  check:
    if: always()
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@v1
        with:
          jobs: ${{ toJSON(needs) }}
